### ISSUE TITLE
No support for videojug videos

### ISSUE THREAD

**Issue by obromios** [calebhearth/fitvids-rails#1]
I find this gem useful, but it does not support videojug videos. The problem appears to be that it currently only supports fitVids v.1.1, whereas videojug support was introduced in fitVids version 2.

This appears to be simply a matter of upgrading the javascript file in vendor assets and changing the versioning.  Would you like me to have a go at this?

**Comment by calebhearth** [comment]
Yeah there should be a rake script to upgrade the version.

**Comment by obromios** [comment]
It turns out I was mistaken and your gem is actually up to date. My problem with videojug is caused by something else.  However, in working on this I found two problems with your rake file in this gem. I have fixed these and sent you a pull request.

By the way, I found your gem most useful, I could not get FitVids working properly using bower-rails.
